const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={project:{name:'Untitled Project',version:1,settings:{aspect:'16:9',fps:30}},assets:[],clips:[],selected:null,history:[],future:[],zoom:100};
const DB='clipora-db',STORE='assets';let dbPromise;
const db=()=>dbPromise||(dbPromise=new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)}));
async function putAsset(a,file){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id:a.id,name:a.name,type:a.type,size:a.size,file});tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
async function hydrate(){try{const d=await db(),rows=await new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});state.assets.forEach(a=>{const row=rows.find(x=>x.id===a.id);if(row?.file)a.url=URL.createObjectURL(row.file)})}catch(e){console.warn(e)}}
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)};
const fmt=s=>{s=Math.max(0,s||0);return `${String(Math.floor(s/60)).padStart(2,'0')}:${(s%60).toFixed(3).padStart(6,'0')}`};
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
function snap(){return JSON.stringify({assets:state.assets.map(({id,name,type,size})=>({id,name,type,size})),clips:state.clips,project:state.project})}function commit(){state.history.push(snap());if(state.history.length>40)state.history.shift();state.future=[]}
function renderTimeline(){const lane=$('#videoTrack');lane.innerHTML='';for(const c of state.clips){const e=document.createElement('div');e.className='clip'+(c.id===state.selected?' selected':'');e.style.left=`${c.start*40*state.zoom/100}px`;e.style.width=`${Math.max(90,(c.end-c.start)*40*state.zoom/100)}px`;e.innerHTML=`<span class="clip-name">${esc(c.name)}</span>`;e.onclick=()=>selectClip(c.id);lane.appendChild(e)}$('#zoomLabel').textContent=`${state.zoom}%`}
function selectClip(id){state.selected=id;const c=state.clips.find(x=>x.id===id);if(c)selectAsset(c.assetId);renderTimeline()}
function selectAsset(id){const a=state.assets.find(x=>x.id===id);if(!a?.url)return;const v=$('#preview');v.src=a.url;v.style.display='block';$('#emptyPreview').style.display='none';v.load();const c=state.clips.find(x=>x.assetId===id);if(c)state.selected=c.id;renderTimeline()}
async function addFiles(files){for(const file of files){const id=crypto.randomUUID(),a={id,name:file.name,type:file.type,size:file.size,url:URL.createObjectURL(file)};state.assets.push(a);await putAsset(a,file);if(file.type.startsWith('video/'))state.clips.push({id:crypto.randomUUID(),assetId:id,name:file.name,start:0,end:0,duration:0})}renderMedia();toast(`${files.length} media item${files.length===1?'':'s'} imported`)}
function renderMedia(){const p=$('#panelContent');$('#mediaCount').textContent=state.assets.length;p.innerHTML=`<div class="upload-box">Drag media here or<label class="primary-btn" style="display:inline-block;cursor:pointer">Browse<input id="panelFileInput" type="file" accept="video/*,audio/*,image/*" multiple hidden></label></div><div style="height:12px"></div>`;state.assets.forEach(a=>{const b=document.createElement('button');b.className='list-button';b.textContent=`${a.type.startsWith('video/')?'🎬':a.type.startsWith('audio/')?'♫':'▧'} ${a.name}`;b.onclick=()=>selectAsset(a.id);p.appendChild(b)});$('#panelFileInput').onchange=e=>addFiles([...e.target.files]);renderTimeline()}
$('#fileInput').onchange=e=>addFiles([...e.target.files]);
$('#preview').onloadedmetadata=()=>{const v=$('#preview'),a=state.assets.find(x=>x.url===v.src),c=a&&state.clips.find(x=>x.assetId===a.id);if(c&&!c.duration){commit();c.duration=v.duration;c.end=v.duration}$('#durationLabel').textContent=fmt(v.duration);$('#resolutionLabel').textContent=`${v.videoWidth}×${v.videoHeight}`;renderTimeline()};$('#preview').ontimeupdate=()=>$('#timeLabel').textContent=fmt($('#preview').currentTime);$('#preview').onended=()=>$('#playBtn').textContent='▶';
$('#playBtn').onclick=()=>{const v=$('#preview');if(!v.src)return toast('Import a video first');if(v.paused){v.play();$('#playBtn').textContent='❚❚'}else{v.pause();$('#playBtn').textContent='▶'}};$('#prevBtn').onclick=()=>$('#preview').currentTime=Math.max(0,$('#preview').currentTime-5);$('#nextBtn').onclick=()=>$('#preview').currentTime=Math.min($('#preview').duration||0,$('#preview').currentTime+5);
$('#ruler').onclick=e=>{$('#preview').currentTime=Math.max(0,Math.min($('#preview').duration||0,((e.clientX-e.currentTarget.getBoundingClientRect().left)/40)*(100/state.zoom)))};
$('#splitBtn').onclick=()=>{const c=state.clips.find(x=>x.id===state.selected),t=$('#preview').currentTime;if(!c||t<=c.start||t>=c.end)return toast('Place playhead inside the selected clip');commit();const r={...c,id:crypto.randomUUID(),start:t,name:c.name+' — 2'};c.end=t;c.name+=' — 1';state.clips.splice(state.clips.indexOf(c)+1,0,r);renderTimeline();toast('Clip split')};$('#deleteBtn').onclick=()=>{if(!state.selected)return;commit();state.clips=state.clips.filter(c=>c.id!==state.selected);state.selected=null;renderTimeline();toast('Clip deleted')};
$('#zoomIn').onclick=()=>{state.zoom=Math.min(300,state.zoom+25);renderTimeline()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(50,state.zoom-25);renderTimeline()};
function saveProject(){localStorage.setItem('clipora.project',snap());toast('Project saved locally')}$('#saveBtn').onclick=saveProject;
function restore(raw){const x=JSON.parse(raw),old=state.assets;state.assets=x.assets.map(a=>({...a,url:old.find(o=>o.id===a.id)?.url||null}));state.clips=x.clips;state.project=x.project;$('#projectName').value=state.project.name;renderMedia();hydrate().then(renderMedia)}
$('#undoBtn').onclick=()=>{const x=state.history.pop();if(!x)return toast('Nothing to undo');state.future.push(snap());restore(x);toast('Undo')};$('#redoBtn').onclick=()=>{const x=state.future.pop();if(!x)return toast('Nothing to redo');state.history.push(snap());restore(x);toast('Redo')};$('#projectName').oninput=e=>state.project.name=e.target.value;
async function exportVideo(){const c=state.clips.find(x=>x.id===state.selected)||state.clips[0],a=c&&state.assets.find(x=>x.id===c.assetId);if(!a?.url)return toast('Import and select a video first');toast('Loading local exporter…');try{const {FFmpeg}=await import('https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@0.12.15/dist/esm/index.js'),{fetchFile}=await import('https://cdn.jsdelivr.net/npm/@ffmpeg/util@0.12.2/dist/esm/index.js'),ff=new FFmpeg();await ff.load({coreURL:'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/esm/ffmpeg-core.js',wasmURL:'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/esm/ffmpeg-core.wasm'});const ext=a.name.includes('.')?a.name.slice(a.name.lastIndexOf('.')):'.mp4',input='source'+ext;await ff.writeFile(input,await fetchFile(a.url));const args=['-i',input];if(c.start>0||c.end<c.duration)args.push('-ss',String(c.start),'-to',String(c.end));args.push('-c:v','libx264','-preset','veryfast','-c:a','aac','clipora-export.mp4');await ff.exec(args);const data=await ff.readFile('clipora-export.mp4'),u=URL.createObjectURL(new Blob([data.buffer],{type:'video/mp4'})),l=document.createElement('a');l.href=u;l.download='clipora-export.mp4';l.click();setTimeout(()=>URL.revokeObjectURL(u),1500);toast('Export complete')}catch(e){console.error(e);toast('Export failed — browser/WASM limitation')}}$('#exportBtn').onclick=exportVideo;
const panels={media:['Media',renderMedia],audio:['Audio',()=>panelMessage('Audio','Audio tracks, voiceover, waveform and mixing are next.')],text:['Text',()=>panelMessage('Text','Text layers and animations are next.')],captions:['Captions',()=>panelMessage('Captions','Whisper/local transcription will plug in here.')],effects:['Effects',()=>panelMessage('Effects','Transitions, filters and keyframes will plug into the timeline.')],settings:['Settings',()=>panelMessage('Settings',`Aspect ${state.project.settings.aspect} · ${state.project.settings.fps} FPS · local-first`)],ai:['AI Agent',renderAI]};function panelMessage(t,b){$('#panelContent').innerHTML=`<div class="panel-card"><h3>${t}</h3><p>${b}</p></div>`}
function renderAI(){$('#panelContent').innerHTML=`<div class="panel-card"><h3>✨ AI Editor</h3><p>AI plans safe editor actions. Nothing is sent anywhere by this built-in planner.</p><textarea id="aiInput" class="ai-input" placeholder="Make this a 30-second Short, remove silence and add captions..."></textarea><button id="aiSend" class="ai-send">Run AI Plan</button><div id="aiResult" class="ai-result"></div></div><div class="panel-card"><h3>Quick actions</h3><button class="list-button ai-quick" data-q="Make this a 30 second vertical Short">Make a Short</button><button class="list-button ai-quick" data-q="Remove boring silent parts">Remove silence</button><button class="list-button ai-quick" data-q="Add captions to this video">Auto captions</button></div>`;$('#aiSend').onclick=runAI;$$('.ai-quick').forEach(b=>b.onclick=()=>{$('#aiInput').value=b.dataset.q;runAI()})}
function planAI(text){const t=text.toLowerCase(),a=[];if(/short|reel|vertical|9:16/.test(t))a.push('Set canvas to 9:16');if(/30.?second|30 sec/.test(t))a.push('Target 30 seconds');if(/silence|boring|remove/.test(t))a.push('Detect and remove low-interest/silent sections');if(/caption|subtitle/.test(t))a.push('Generate timed captions');if(/music|audio/.test(t))a.push('Prepare audio mix');return a.length?a:['Analyze the timeline and propose a safe edit']}
function runAI(){const text=$('#aiInput')?.value.trim();if(!text)return;const actions=planAI(text);$('#aiResult').innerHTML='<strong>PLAN</strong><br>'+actions.map((x,i)=>`${i+1}. ${esc(x)}`).join('<br>')+'<br><br><button id="applyAI" class="ai-send">Apply safe commands</button>';$('#applyAI').onclick=()=>{commit();if(/short|reel|vertical|9:16/i.test(text))state.project.settings.aspect='9:16';toast('AI plan applied');renderTimeline()}}
$$('.tool,.mobile-tools button').forEach(b=>b.onclick=()=>{const p=panels[b.dataset.panel];if(!p)return;$('#panelTitle').textContent=p[0];p[1]();$('#leftPanel').classList.toggle('open',innerWidth<=900);$$('.tool').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.panel))});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files.length)addFiles([...e.dataTransfer.files])});window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveProject()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('#undoBtn').click()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();$('#redoBtn').click()}if(e.code==='Space'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#playBtn').click()}if(e.key.toLowerCase()==='c'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))$('#splitBtn').click()});
(async()=>{const saved=localStorage.getItem('clipora.project');if(saved){try{restore(saved)}catch{renderMedia()}}else renderMedia();await hydrate();renderMedia()})();