(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const KEY='clipora.project.v3', DB='clipora-db-v3', STORE='assets';
  const state={project:{name:'Untitled Project',version:3,settings:{aspect:'16:9',fps:30}},assets:[],clips:[],audio:[],texts:[],captions:[],effects:[],selected:null,history:[],future:[],zoom:100};
  let dbp;
  const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2200)};
  const id=()=>crypto.randomUUID();
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fmt=s=>{s=Math.max(0,Number(s)||0);return `${String(Math.floor(s/60)).padStart(2,'0')}:${(s%60).toFixed(3).padStart(6,'0')}`};
  function db(){return dbp||(dbp=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}))}
  async function saveBlob(asset,file){const d=await db();return new Promise((ok,no)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put({id:asset.id,name:asset.name,type:asset.type,size:asset.size,file});tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
  async function loadBlobs(){const d=await db();return new Promise((ok,no)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
  function serial(){return JSON.stringify({project:state.project,assets:state.assets.map(a=>({id:a.id,name:a.name,type:a.type,size:a.size})),clips:state.clips,audio:state.audio,texts:state.texts,captions:state.captions,effects:state.effects})}
  function persist(){localStorage.setItem(KEY,serial());localStorage.setItem('clipora.project',serial())}
  function snapshot(){return serial()}
  function commit(){state.history.push(snapshot());if(state.history.length>30)state.history.shift();state.future=[]}
  async function restore(raw){const x=JSON.parse(raw);state.project=x.project||state.project;state.assets=x.assets||[];state.clips=x.clips||[];state.audio=x.audio||[];state.texts=x.texts||[];state.captions=x.captions||[];state.effects=x.effects||[];state.selected=null;const rows=await loadBlobs();rows.forEach(r=>{const a=state.assets.find(x=>x.id===r.id);if(a)a.url=URL.createObjectURL(r.file)});$('#projectName').value=state.project.name||'Untitled Project';renderMedia();renderTimeline();applyCanvas();persist()}
  async function boot(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem('clipora.project');if(raw)await restore(raw);else{renderMedia();renderTimeline();applyCanvas()}}catch(e){console.error(e);renderMedia();renderTimeline()}}
  function applyCanvas(){const a=state.project.settings.aspect||'16:9',stage=$('#previewStage');if(stage){stage.style.aspectRatio=a.replace(':','/');stage.dataset.aspect=a}}
  function asset(id){return state.assets.find(a=>a.id===id)}
  function clip(id){return state.clips.find(c=>c.id===id)}
  function selectClip(cid){state.selected=cid;const c=clip(cid);if(c)selectAsset(c.assetId);renderTimeline()}
  function selectAsset(aid){const a=asset(aid);if(!a?.url)return toast('Media is unavailable — re-import it');const v=$('#preview');v.src=a.url;v.load();v.style.display='block';$('#emptyPreview').style.display='none';const c=state.clips.find(x=>x.assetId===aid);if(c)state.selected=c.id;renderTimeline()}
  function renderTimeline(){const lane=$('#videoTrack');if(!lane)return;lane.innerHTML='';const z=state.zoom/100;state.clips.forEach(c=>{const e=document.createElement('div');e.className='clip'+(c.id===state.selected?' selected':'');e.style.left=`${c.start*40*z}px`;e.style.width=`${Math.max(80,(c.end-c.start)*40*z)}px`;e.innerHTML=`<span class="clip-name">${esc(c.name)}</span>`;e.onclick=()=>selectClip(c.id);lane.appendChild(e)});const rows=$$('.track-row');const draw=(row,items,label)=>{const lane=row?.querySelector('.track-lane');if(!lane)return;lane.innerHTML='';items.forEach(x=>{const e=document.createElement('div');e.className='clip';e.style.left=`${Number(x.start||0)*40*z}px`;e.style.width=`${Math.max(80,Number(x.duration||3)*40*z)}px`;e.innerHTML=`<span class="clip-name">${label}${esc(x.text||x.name||'')}</span>`;lane.appendChild(e)})};draw(rows[1],state.audio,'♫ ');draw(rows[2],state.captions,'CC ');draw(rows[3],state.effects,'✦ ');$('#zoomLabel').textContent=`${state.zoom}%`}
  async function addFiles(files){if(!files.length)return;let firstVideo=null;for(const file of files){const aid=id(),a={id:aid,name:file.name,type:file.type,size:file.size,url:URL.createObjectURL(file)};state.assets.push(a);await saveBlob(a,file);if(file.type.startsWith('video/')){const c={id:id(),assetId:aid,name:file.name,start:0,end:0,duration:0};state.clips.push(c);if(!firstVideo)firstVideo=c.id}else if(file.type.startsWith('audio/')){state.audio.push({id:id(),assetId:aid,name:file.name,start:0,duration:0,volume:1})}else if(file.type.startsWith('image/')){state.clips.push({id:id(),assetId:aid,name:file.name,start:0,end:5,duration:5,image:true})}}persist();renderMedia();if(firstVideo)selectClip(firstVideo);toast(`${files.length} file${files.length>1?'s':''} imported`)}
  function renderMedia(){const p=$('#panelContent');if(!p)return;$('#mediaCount').textContent=state.assets.length;p.innerHTML=`<div class="upload-box">Import media <label class="primary-btn" style="display:inline-block;cursor:pointer">Browse<input id="panelFileInput" type="file" accept="video/*,audio/*,image/*" multiple hidden></label></div><div style="height:10px"></div>`;state.assets.forEach(a=>{const b=document.createElement('button');b.className='list-button';b.textContent=`${a.type.startsWith('video/')?'🎬':a.type.startsWith('audio/')?'♫':'▧'} ${a.name}`;b.onclick=()=>selectAsset(a.id);p.appendChild(b)});$('#panelFileInput').onchange=e=>addFiles([...e.target.files]);renderTimeline()}
  function card(title,html){$('#panelContent').innerHTML=`<div class="panel-card"><h3>${title}</h3>${html}</div>`}
  function renderAudio(){card('Audio',`<p>Import music or voiceover. It is placed on the audio track.</p><label class="list-button" style="display:block;cursor:pointer">＋ Import audio<input id="audioInput" type="file" accept="audio/*" multiple hidden></label>${state.audio.map(a=>`<button class="list-button">♫ ${esc(a.name)}</button>`).join('')||'<p>No audio yet.</p>'}`);$('#audioInput').onchange=e=>addFiles([...e.target.files])}
  function renderText(){card('Text',`<p>Add a title at the current playhead.</p><input id="textValue" class="ai-input" placeholder="Your title"><button id="addText" class="ai-send">＋ Add text</button>${state.texts.map(x=>`<button class="list-button">T ${esc(x.text)}</button>`).join('')}`);$('#addText').onclick=()=>{const text=$('#textValue').value.trim();if(!text)return toast('Enter text first');commit();state.texts.push({id:id(),text,start:$('#preview').currentTime||0,duration:4});persist();renderText();renderTimeline();toast('Text added')};}
  function renderCaptions(){card('Captions',`<p>Add captions manually or use AI transcription.</p><textarea id="captionInput" class="ai-input" placeholder="Caption text"></textarea><button id="addCaption" class="ai-send">＋ Add caption</button><button id="transcribeBtn" class="list-button">🎙 Transcribe with local Whisper</button>${state.captions.map(x=>`<button class="list-button">CC ${esc(x.text)}</button>`).join('')}`);$('#addCaption').onclick=()=>{const text=$('#captionInput').value.trim();if(!text)return toast('Enter caption text');commit();state.captions.push({id:id(),text,start:$('#preview').currentTime||0,duration:4});persist();renderCaptions();renderTimeline();toast('Caption added')};$('#transcribeBtn').onclick=()=>window.CliporaLocalAI?.transcribe?.()||toast('Local AI engine is unavailable')}
  function renderEffects(){card('Effects',`<p>Select a video clip, then apply an effect.</p><button class="list-button" data-effect="Fade in">Fade in</button><button class="list-button" data-effect="Slow zoom">Slow zoom</button><button class="list-button" data-effect="Mute">Mute</button><button class="list-button" data-effect="1.5× speed">1.5× speed</button>`);$$('[data-effect]').forEach(b=>b.onclick=()=>{const c=clip(state.selected);if(!c)return toast('Select a video clip first');commit();state.effects.push({id:id(),name:b.dataset.effect,start:c.start,duration:Math.max(.1,c.end-c.start)});persist();renderTimeline();toast(`${b.dataset.effect} added`)})}
  function renderSettings(){card('Settings',`<p>Canvas</p><select id="aspectSelect" class="list-button"><option>16:9</option><option>9:16</option><option>1:1</option><option>4:5</option></select><button id="downloadProject" class="list-button">Export project JSON</button><label class="list-button" style="display:block;cursor:pointer">Import project JSON<input id="importProject" type="file" accept="application/json" hidden></label>`);$('#aspectSelect').value=state.project.settings.aspect;$('#aspectSelect').onchange=e=>{commit();state.project.settings.aspect=e.target.value;applyCanvas();persist();toast(`Canvas ${e.target.value}`)};$('#downloadProject').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([serial()],{type:'application/json'}));a.href=u;a.download='clipora-project.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('#importProject').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{commit();await restore(r.result);toast('Project imported')}catch(x){toast('Invalid project')}};r.readAsText(f)}}
  function renderAI(){card('AI Editor',`<p>Local rule-based editing works without an API.</p><textarea id="aiInput" class="ai-input" placeholder="Make it vertical, add a title and captions…"></textarea><button id="aiSend" class="ai-send">✦ Run AI action</button><button class="list-button" data-ai="9:16">Make 9:16</button><button class="list-button" data-ai="title">Add title</button><button class="list-button" data-ai="caption">Add caption</button><button class="list-button" data-ai="trim30">Trim to 30 seconds</button><div id="aiResult" class="ai-result"></div>`);$('#aiSend').onclick=()=>runAI($('#aiInput').value);$$('[data-ai]').forEach(b=>b.onclick=()=>runAI(b.dataset.ai))}
  function runAI(text){const t=String(text||'').toLowerCase(),out=[];if(/9:16|vertical|short|reel/.test(t)){commit();state.project.settings.aspect='9:16';applyCanvas();out.push('Canvas set to 9:16')}if(/title|text/.test(t)){commit();state.texts.push({id:id(),text:'Your title',start:$('#preview').currentTime||0,duration:4});out.push('Title added')}if(/caption|subtitle/.test(t)){commit();state.captions.push({id:id(),text:'Your caption',start:$('#preview').currentTime||0,duration:4});out.push('Caption added')}if(/30|trim/.test(t)&&state.clips.length){commit();const c=state.clips[0];c.end=Math.min(c.start+30,c.end||c.start+30);out.push('Clip limited to 30 seconds')}persist();renderTimeline();$('#aiResult').innerHTML=out.length?out.map(esc).join('<br>'):'No automatic action matched';toast(out.length?'AI action completed':'No action matched')}
  const panels={media:['Media',renderMedia],audio:['Audio',renderAudio],text:['Text',renderText],captions:['Captions',renderCaptions],effects:['Effects',renderEffects],ai:['AI Editor',renderAI],settings:['Settings',renderSettings]};
  function openPanel(k){const p=panels[k];if(!p)return;$('#panelTitle').textContent=p[0];p[1]();$$('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===k));}
  $$('.sidebar [data-panel],.mobile-tools [data-panel]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));
  $('#fileInput')?.addEventListener('change',e=>addFiles([...e.target.files]));
  $('#saveBtn')?.addEventListener('click',()=>{persist();toast('Project saved locally')});
  $('#projectName')?.addEventListener('input',e=>{state.project.name=e.target.value;persist()});
  $('#playBtn')?.addEventListener('click',()=>{const v=$('#preview');if(!v.src)return toast('Import a video first');if(v.paused){v.play();$('#playBtn').textContent='❚❚'}else{v.pause();$('#playBtn').textContent='▶'}});
  $('#prevBtn')?.addEventListener('click',()=>{$('#preview').currentTime=Math.max(0,$('#preview').currentTime-5)});
  $('#nextBtn')?.addEventListener('click',()=>{$('#preview').currentTime=Math.min($('#preview').duration||0,$('#preview').currentTime+5)});
  $('#fitBtn')?.addEventListener('click',()=>{$('#preview').style.objectFit=$('#preview').style.objectFit==='cover'?'contain':'cover'});
  $('#preview')?.addEventListener('loadedmetadata',()=>{const v=$('#preview'),a=state.assets.find(x=>x.url===v.src),c=a&&state.clips.find(x=>x.assetId===a.id);if(c&&!c.duration){c.duration=v.duration;c.end=v.duration;persist();renderTimeline()}$('#durationLabel').textContent=fmt(v.duration);$('#resolutionLabel').textContent=`${v.videoWidth}×${v.videoHeight}`});
  $('#preview')?.addEventListener('timeupdate',()=>{$('#timeLabel').textContent=fmt($('#preview').currentTime)});
  $('#splitBtn')?.addEventListener('click',()=>{const c=clip(state.selected),t=$('#preview').currentTime;if(!c||t<=c.start+.01||t>=c.end-.01)return toast('Put the playhead inside a selected clip');commit();const right={...c,id:id(),start:t,name:c.name+' 2'};c.end=t;c.name+=' 1';state.clips.splice(state.clips.indexOf(c)+1,0,right);persist();renderTimeline();toast('Clip split')});
  $('#deleteBtn')?.addEventListener('click',()=>{if(!state.selected)return toast('Select a clip first');commit();state.clips=state.clips.filter(c=>c.id!==state.selected);state.selected=null;persist();renderTimeline();toast('Clip deleted')});
  $('#zoomIn')?.addEventListener('click',()=>{state.zoom=Math.min(400,state.zoom+25);renderTimeline()});
  $('#zoomOut')?.addEventListener('click',()=>{state.zoom=Math.max(50,state.zoom-25);renderTimeline()});
  $('#ruler')?.addEventListener('click',e=>{const r=e.currentTarget.getBoundingClientRect(),sec=((e.clientX-r.left)/40)*(100/state.zoom);$('#preview').currentTime=Math.max(0,Math.min($('#preview').duration||0,sec))});
  $('#undoBtn')?.addEventListener('click',async()=>{const x=state.history.pop();if(!x)return toast('Nothing to undo');state.future.push(snapshot());await restore(x);toast('Undo')});
  $('#redoBtn')?.addEventListener('click',async()=>{const x=state.future.pop();if(!x)return toast('Nothing to redo');state.history.push(snapshot());await restore(x);toast('Redo')});
  $('#exportBtn')?.addEventListener('click',()=>window.CliporaExporter?.exportProject?.()||toast('Export engine is unavailable'));
  window.CliporaState={state,serial,asset,loadBlobs,persist,toast,renderTimeline,renderMedia,openPanel};
  window.addEventListener('DOMContentLoaded',()=>{boot();openPanel('media')});
})();