/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaptionGeneratorRouteImport } from './routes/caption-generator'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'

const CaptionGeneratorRoute = CaptionGeneratorRouteImport.update({
  id: '/caption-generator',
  path: '/caption-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caption-generator': typeof CaptionGeneratorRoute
  '/editor': typeof EditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caption-generator': typeof CaptionGeneratorRoute
  '/editor': typeof EditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caption-generator': typeof CaptionGeneratorRoute
  '/editor': typeof EditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caption-generator' | '/editor'
  fileRoutesByTo: FileRoutesByTo
  id: '__root__' | '/' | '/caption-generator' | '/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptionGeneratorRoute: typeof CaptionGeneratorRoute
  EditorRoute: typeof EditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/caption-generator': {
      id: '/caption-generator'
      path: '/caption-generator'
      fullPath: '/caption-generator'
      preLoaderRoute: typeof CaptionGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptionGeneratorRoute: CaptionGeneratorRoute,
  EditorRoute: EditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
